require: rubocop-rails
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
Layout/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'config/environments/**/*'
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*'
